# Stage 1: Build React app
FROM node:16-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Serve with Nginx
FROM node:16-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["npm","start"]
