name: OWASP ZAP DAST

on:
    workflow_dispatch:

jobs:
  # Phase 4: OWASP ZAP DAST
  zap-dast:
    name: OWASP ZAP DAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Deploy
        run: docker-compose -f app-services/docker-compose.yml up -d --build

      - name: Wait for app to start
        run: sleep 15

      - name: Health Check
        run: curl -f http://localhost:3000 || exit 1

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        continue-on-error: true
        with:
          target: 'http://localhost:3000'
          report_md: 'zap-report.md'
          report_html: 'zap-report.html'
          report_json: 'zap-report.json'
          cmd_options: '-a -I'

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4 
        with:
          name: zap-security-reports
          path: |
            zap-report.html
            zap-report.json  
            zap-report.md
          retention-days: 1

      - name: Tear Down
        if: always()
        run: docker-compose -f app-services/docker-compose.yml down
