name: SonarQube Analysis

on:
    workflow_dispatch:

jobs:
  # Phase 2: SonarQube SAST
  sonar-scan:
    name: SonarQube Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Install dependencies for all services
        run: |
            for dir in app-services/*; do
            if [ -f "$dir/package.json" ]; then
                echo "Installing dependencies in $dir"
                (cd "$dir" && npm ci)
            fi
            done

      - name: Debug SonarQube Connection
        run: |
          echo "SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}"
          echo "SONAR_TOKEN length: ${#SONAR_TOKEN}"
          # Test basic connectivity (without revealing token)
          if curl -s --head --request GET ${{ secrets.SONAR_HOST_URL }} | grep "200 OK"; then
            echo "✅ SonarQube server is reachable"
          else
            echo "❌ Cannot reach SonarQube server"
          fi

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=devsecops-blog-app
            -Dsonar.projectName="DevSecOps Blog Application"
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
      
      - name: Check Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@master
        continue-on-error: true
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

